@base = http://localhost:5102/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2QyNWRjMzU4N2YzNGEyMDAwOGRiN2QiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImp0aSI6IjY1YTU2NzhiLWRmZGUtNDNiYi04NjI0LTgwMDY5MDE0MTI4MyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6ImFkbWluIiwiZXhwIjoxNzQxODkzOTAwLCJpc3MiOiJtaWN3LmNvbSIsImF1ZCI6Im1pY3cuY29tIn0.DeYbHhl0_XfE8txMTPVVfuaQANlXwJODfRXdED-zKMM
@idGet = 67d25dc3587f34a20008db7d
### 1️⃣ Đăng ký user (Create User)
POST {{base}}/user/register
Content-Type: application/json

{
    "email": "user@user.com",
    "password": "123456789",
    "fullName": "user",
    "role": "user"
}

### 2️⃣ Đăng nhập user (Login)
POST {{base}}/user/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "123456789"
}

### 3️⃣ Lấy danh sách users (Read All Users) - Cần quyền admin
GET {{base}}/user
Authorization: Bearer {{token}}

### 4️⃣ Lấy thông tin user theo ID (Read One User)
GET {{base}}/user/67d25dc3587f34a20008db7d
# Authorization: Bearer {{TOKEN}}

### 5️⃣ Cập nhật thông tin user (Update User)
PUT {{base}}/user/{{idGet}}
Content-Type: application/json
# Authorization: Bearer {{TOKEN}}

{
    "email": "dat@example.com",
    "fullName": "Đạt Nguyễn",
    "role": "user"
}

### 6️⃣ Xóa user theo ID (Delete User)
DELETE {{base}}/user/1
# Authorization: Bearer {{TOKEN}}
